name: Build and Push Agent Image

on:
  push:
    branches: [ '**' ]
    tags: [ 'v*' ]
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Extract metadata
        id: meta
        run: |
          # If this is a release event
          if [[ "${{ github.event_name }}" == "release" ]]; then
            # Get version from release tag without v prefix
            echo "tag=$(echo ${{ github.event.release.tag_name }} | sed 's/^v//')" >> $GITHUB_OUTPUT
            echo "is_release=true" >> $GITHUB_OUTPUT
          # If this is a branch push
          elif [[ "${{ github.ref_type }}" == "branch" ]]; then
            echo "tag=$(echo ${{ github.ref_name }} | sed 's/\//-/g')" >> $GITHUB_OUTPUT
            echo "is_release=false" >> $GITHUB_OUTPUT
          # If this is a tag push
          else
            # For tags, remove the 'v' prefix for version numbers
            echo "tag=$(echo ${{ github.ref_name }} | sed 's/^v//')" >> $GITHUB_OUTPUT
            echo "is_release=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push Agent
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.agent
          push: true
          tags: |
            ${{ steps.meta.outputs.is_release == 'true' && 'ghcr.io/edgetainer/edgetainer/agent:latest' || '' }}
            ghcr.io/edgetainer/edgetainer/agent:${{ steps.meta.outputs.tag }}
